name: flureadium_example
description: 'Minimal example demonstrating the flureadium plugin.'
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flureadium:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
  assets:
    - assets/pubs/
    - assets/webManifestList.json
