name: flutter_readium_example
description: 'Demonstrates how to use the flutter_readium plugin.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker:
  flutter_bloc:
  flutter_readium:
    # When depending on this package from a real application you should use:
    #   flutter_readium: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  native_device_orientation:
  path:
  path_provider:

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  disable-swift-package-manager: true
  assets:
    - assets/pubs/
